name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 0 */2 * *"
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: https://wakatime.com/share/@3b5f442c-0f4a-4621-9df5-3641fafed13f/0a346458-352a-4376-8dfa-c0ea50c04814.json
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          SHOW_TITLE: true
